version: '3'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase
    restart: always

  importer:
    build:
      context: ./importer # TODO: pull from docker-hub?
    depends_on:
      - postgres
  # TODO: dperson/samba
