version: '3'
services:
  metabase-app:
    volumes:
      - ./metabase-data:/metabase-data # TODO: remove? useless if using posgres??
    ports:
      - 80:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metadata
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    links:
      - postgres

  importer:
    command: sh -c './wait-for.sh postgres:5432 -- npm run start'
    volumes:
      - ./data:/data # TODO: dev only??

